apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "text2sql-editor.fullname" . }}
  namespace: default
subjects:
- kind: User
  name: "jovyan"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ include "text2sql-editor.fullname" . }}
  apiGroup: rbac.authorization.k8s.io


